<div>
    <pre>
各位老师，您好：
	应用${project_name}已准备投产打包，任务${name}包含未经审核的关联项，请及时通过任务${name}的关联项审核。
关联项审核链接：xxx${port}/fdev/#/release/list/${release_node_name}/joblist
投产任务详情：
	投产任务名称：${name}
	投产应用名称：${project_name}
	投产点名称：${release_node_name}
	任务描述:${desc}
	实施单元编号:${redmine_id}
    <br><br>
</pre>
</div>
