---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG
  namespace: common
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG
          image: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
          env:
            - name: CI_PROJECT_NAME
              value: $CI_PROJECT_NAME
            - name: CI_ENVIRONMENT_SLUG
              value: $CI_ENVIRONMENT_SLUG
            - name: SW_AGENT_NAME
              value: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG
            - name: SW_AGENT_NAMESPACE
              value: $CI_ENVIRONMENT_SLUG
            - name: SW_MONGODB_TRACE_PARAM
              value: "true"
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value:xxx:11800,xxx:11800,xxx:11800
            - name: SW_AGENT_TRACE_IGNORE_PATH
              value: /fwebhook/actuator/*
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: log
              mountPath: /fdev/log
            - name: skywalking
              mountPath: /usr/skywalking/agent
          livenessProbe:
            httpGet:
              path: /fwebhook/actuator/info
              port: 8080
              httpHeaders:
                - name: source
                  value: back
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: source
                  value: back
              path: /fwebhook/actuator/info
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 0
              memory: 0
      volumes:
        - name: log
          hostPath:
            path: /home/ebank/spdb/fdev/log/fwebhook/$CI_ENVIRONMENT_SLUG
        - name: skywalking
          hostPath:
            path: /home/ebank/spdb/fdev/skywalking/agent

---
apiVersion: v1
kind: Service
metadata:
  name: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG-svc
  namespace: common
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG-ingress
  namespace: common
spec:
  rules:
    - host: $CI_PROJECT_NAME.$CI_ENVIRONMENT_SLUG.minikube
      http:
        paths:
          - backend:
              serviceName: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG-svc
              servicePort: 8080
            path: /
