FROM xxx/library/frelease-base:latest

ENV LANG "en_US.utf8"
ENV TZ Asia/Shanghai

ADD fdev-component-0.0.1-SNAPSHOT.jar  /ebank/app.jar
ADD start.sh /ebank/start.sh
ADD apache-maven-3.6.0-bin.tar.gz /usr/share
COPY settings.xml /usr/share/apache-maven-3.6.0/conf/settings.xml
COPY scripts/* /scripts/

ENV PATH=/usr/share/apache-maven-3.6.0/bin:/usr/share/jdk1.8.0_151/bin:$PATH

ENTRYPOINT ["sh" , "/ebank/start.sh"]