export default {
  fuser: {
    createAuthCode: '/fuser/api/auth/createAuthCode',
    forgetPassWord: '/fuser/api/auth/forgetPassWord',
    getVerifyCode: '/fuser/api/auth/getVerifyCode',
    login: '/fuser/api/auth/login',
    onceLogin: '/fuser/api/auth/onceLogin',
    queryOAuth: '/fuser/api/auth/queryOAuth',
    companyAdd: '/fuser/api/company/add',
    companyDelete: '/fuser/api/company/delete',
    companyQuery: '/fuser/api/company/query',
    companyUpdate: '/fuser/api/company/update',
    groupAdd: '/fuser/api/group/add',
    groupDelete: '/fuser/api/group/delete',
    groupQuery: '/fuser/api/group/query',
    queryByGroupId: '/fuser/api/group/queryByGroupId',
    queryChildGroupById: '/fuser/api/group/queryChildGroupById',
    groupUpdate: '/fuser/api/group/update',
    labelAdd: '/fuser/api/label/add',
    labelDelete: '/fuser/api/label/delete',
    labelQuery: '/fuser/api/label/query',
    permissionQuery: '/fuser/api/permission/query',
    permissionUpdate: '/fuser/api/permission/update',
    roleAdd: '/fuser/api/role/add',
    roleDelete: '/fuser/api/role/delete',
    roleQuery: '/fuser/api/role/query',
    roleUpdate: '/fuser/api/role/update',
    userAdd: '/fuser/api/user/add',
    currentUser: '/fuser/api/user/currentUser',
    userDelete: '/fuser/api/user/delete',
    userQuery: '/fuser/api/user/query',
    queryUserCoreData: '/fuser/api/user/queryUserCoreData',
    userUpdate: '/fuser/api/user/update',
    updateUserIsOnceLogin: '/fuser/api/user/updateUserIsOnceLogin',
    queryCommissionEvent: '/fuser/api/userCommissionEvent/queryCommissionEvent',
    updateLabelById: '/fuser/api/userCommissionEvent/updateLabelById',
    simulateUser: '/fuser/api/auth/simulateUser',
    resetPassword: '/fuser/api/auth/updatePassword',
    queryArea: '/fuser/api/user/queryArea',
    queryUserStatis: '/fuser/api/user/queryUserStatis',
    queryFunction: '/fuser/api/user/queryfunction',
    queryRank: '/fuser/api/user/queryrank',
    queryTaskNumByGroup: '/fuser/api/user/queryTaskNumByGroup',
    getJobUser: '/fuser/api/user/getJobUser',
    queryUserPagination: '/fuser/api/user/queryUser',
    queryReBuildGroupName: '/fuser/api/group/reBuildGroupName',
    queryGroup: '/fuser/api/group/queryGroup',
    queryApprovalList: '/fuser/api/approval/queryApprovalList',
    updateApprovalStatus: '/fuser/api/approval/updateApprovalStatus',
    queryRoleForLDAP: '/fuser/api/role/queryRoleForLDAP',
    updateGitToken: '/fuser/api/user/updateGitToken',
    queryIpmpLeadTeam: '/fuser/api/ipmpTeam/queryIpmpLeadTeam', //查询牵头单位和团队信息
    queryIpmpUser: '/fuser/api/ipmpUser/queryIpmpUser' //查询ipmp人员信息
  },
  ftask: {
    queryUserTask: '/ftask/api/task/queryUserTask',
    taskUpdate: '/ftask/api/task/update'
  }
};
