// Code generated by mockery v2.5.1. DO NOT EDIT.

package common

import (
	context "context"
	mock "github.com/stretchr/testify/mock"
	"os"
)

// MockJobTrace is an autogenerated mock type for the JobTrace type
type MockJobTrace struct {
	mock.Mock
}

// Fail provides a mock function with given fields: err, failureReason
func (_m *MockJobTrace) Fail(err error, failureReason JobFailureReason) {
	_m.Called(err, failureReason)
}

// GetState provides a mock function with given fields:
func (_m *MockJobTrace) GetState() JobState {
	ret := _m.Called()

	var r0 JobState
	if rf, ok := ret.Get(0).(func() JobState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(JobState)
	}

	return r0
}

// IsStdout provides a mock function with given fields:
func (_m *MockJobTrace) IsStdout() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetCancelFunc provides a mock function with given fields: cancelFunc
func (_m *MockJobTrace) SetCancelFunc(cancelFunc context.CancelFunc) {
	_m.Called(cancelFunc)
}

// SetFailuresCollector provides a mock function with given fields: fc
func (_m *MockJobTrace) SetFailuresCollector(fc FailuresCollector) {
	_m.Called(fc)
}

// SetMasked provides a mock function with given fields: values
func (_m *MockJobTrace) SetMasked(values []string) {
	_m.Called(values)
}

// Success provides a mock function with given fields:
func (_m *MockJobTrace) Success() {
	_m.Called()
}

// Write provides a mock function with given fields: p
func (_m *MockJobTrace) Write(p []byte) (int, error) {
	return os.Stdout.Write(p)
}
