<div>
    <pre>
各位老师好：
    以下内容为 ${updateTaskUser} 在测试管理平台修改的工单进入 <b>uat</b> 状态 的信息 ：
    工单编号：${workOrderNo}
    工单名称：${mainTaskName}
    所属阶段：${stage}
    需求编号/实施单元：${unit}
    计划Sit测试时间：${planSitDate}
    计划Uat时间：${planUatDate}
    计划投产时间：${planProDate}
    uat提测时间：${uatSubmitDate}
    工单标识：${workOrderFlag}
    工单管理员：${workManager}
    工单组长：${groupLeader}
    审批人员：${field2}
    测试人员：${testers}
    工单创建时间：${field3}
    工单备注：${remark}
    <br><br>
</pre>
</div>
