FROM docker:17.11.0-ce-dind
MAINTAINER "xxx"

ENV PATH=/opt/fdev-helper:$PATH

# 更换 aliyun 源
RUN echo "" > /etc/apk/repositories ;\
  echo "http://mirrors.aliyun.com/alpine/v3.6/main" >> /etc/apk/repositories ;\
  echo "http://mirrors.aliyun.com/alpine/v3.6/community" >> /etc/apk/repositories ;\
  apk update

# 安装 pre-req
RUN apk add -U openssl curl tar gzip bash ca-certificates git wget jq libintl coreutils \
   && apk add --virtual build_deps gettext \
   && mv /usr/bin/envsubst /usr/local/bin/envsubst \
   && apk del build_deps

# 安装 kubeval
COPY kubectl /usr/local/bin
COPY kubeval /usr/local/bin
RUN chmod +x /usr/local/bin/*

# 安装 python
COPY get-pip.py /root
RUN apk add python && python /root/get-pip.py && pip install pyyaml && pip install SSHClient && pip install SCPClient
RUN apk add openssh && pip install pexpect && pip install chardet